### ISSUE TITLE
Gallery (Image Viewer) should show videos as well

### ISSUE THREAD

**Issue by Sherlock1979** [owncloud/apps#1437]
Hi,

I think that the gallery (image viewer) app should display the videos, if the video player app is enabled as well.

I guess it would not be that hard to implement as the video player already plays videos from file browser. It would be awesome to implement.

What do you think?

David

**Comment by 1cu** [comment]
Any update on this - currently it's pretty unstatisfing to browse my media in owncloud.

**Comment by jancborchardt** [comment]
@oparoz for reference for the new Gallery app.

**Comment by oparoz** [comment]
Thanks. The biggest problem is trying to mix the 2 players together. They use different styling, etc. Also, the bigshot library should support video soon, with zooming, etc., so that could be an alternative player... I haven't looked at the JS in details to know for sure.

As far as thumbnails are concerned, they're easy to add to the mix, but they need a play button overlay.

**Comment by jancborchardt** [comment]
We don’t really need zooming for videos. Pictures and videos should show both the same in the overview and in the detail slideshow. (Except of course for the play button overlay you mentioned.)

**Comment by oparoz** [comment]
Closing this in favour of https://github.com/owncloud/galleryplus/issues/194
