### ISSUE TITLE
[Gallery] Transition when switching pics in slideshow

### ISSUE THREAD

**Issue by PVince81** [owncloud/apps#1503]
When slideshow is enabled, quickly fade to the next pic.
When the user clicks prev/next, don't animate as it might be annoying.

This is possible with CSS3. The pre-requisite is that the next picture(s) need to be preloaded.

If the animation is fast enough, there is no need to make this configurable.

**Comment by jancborchardt** [comment]
@oparoz is a quick fade (very quick, like 300ms maybe) possible for Gallery+?

**Comment by oparoz** [comment]
I gave it a go and got horrible results... but that's because instead of having multiple DOM elements which could be switched between one another, we detach the picture and re-attach one. Images are pre-loaded though.

Already referenced in Gallery here https://github.com/owncloud/galleryplus/issues/83

**Comment by jancborchardt** [comment]
@oparoz you can also close this one in favor of the issue in galleryplus then ;)
