### ISSUE TITLE
Anti Virus App improvements

### ISSUE THREAD

**Issue by karlitschek** [owncloud/apps#1671]
We need a few improvements in the Anti-Virus App

 - Ability to call external virus scan apps 
We need a way to specify custom command and command line options and return codes so that we can integrate other virus scanners then clamav

- Optionally show a warning in the Webinterface and in the Activity app if a virus is found.
- Optionally add a custom WebDAV property so that the Desktop and Mobile Apps can show a red cross overlay icon on the clients

**Comment by DeepDiver1975** [comment]
we should move this over to https://github.com/owncloud/files_antivirus

**Comment by VicDeo** [comment]
- [x] Ability to call external virus scan apps We need a way to specify custom command and command line options and return codes so that we can integrate other virus scanners then clamav 
_Technically possible right now. But I have no idea what  other scanners are available_

- [x] Optionally show a warning in the Webinterface and in the Activity app if a virus is found.
_Done_

- [ ] Optionally add a custom WebDAV property so that the Desktop and Mobile Apps can show a red cross overlay icon on the clients
_Not implemented_
