### ISSUE TITLE
Unable to list files/folders using Http/WebDAV client for php

### ISSUE THREAD

**Issue by prakashwadhwani** [owncloud/apps#2050]
​Although the PROPFIND request returns the correct xml from the terminal we are unable to access any files/folders using the PROPFIND verb from the WebDAV client by sabre. (http://sabre.io/dav/davclient/)

Have also tried it using guzzle, but getting the same response object.

Code

            $settings = array(
                'baseUri' => $url,
                'userName' => $username,
                'password' => $password,
                );

            $client = new SabreClient($settings);
            $response = $client->propfind($url, array(
                '{DAV:}displayname',
                '{DAV:}getcontentlength',
                ));

The response is,

    Array
    (
        [{http://owncloud.org/ns}id] => 00000055oc7kjmpoe4t8
        [{http://owncloud.org/ns}permissions] => RDNVCK
        [{http://owncloud.org/ns}size] => 2754651
    )

Server configuration:
CentOS 6.6 (Final)
nginx 1.6.2
PHP 5.5.23
ownCloud version 8.0.2

If you need any more information, please comment below. Thanks.

**Comment by RealRancor** [comment]
Hi,

this don't looks like an issue with an app itself (which this issue tracker is about) but more like a core problem.

**Comment by PVince81** [comment]
What response are you getting ?

What is the value of $url, does it correctly point to "remote.php/webdav/" ?

**Comment by PVince81** [comment]
Closing due to lack of feedback.

Please check whether a regular Webdav client (cadaver, dolphin or other) is able to access the folders.
If it is, then maybe the URL you are using in the PHP code isn't correct.

Also the response you posted doesn't match the requested attributes for some reason. Are you sure you posted the result of this exact piece of code and not the response of another test run ?

Also, please upgrade to 8.0.9. 8.0.2 is already quite old and if there was a bug, it is very likely that it was fixed already.

Thanks.
