### ISSUE TITLE
Better Support for Reccuring Events

### ISSUE THREAD

**Issue by georgehrke** [owncloud/apps#33]
Better support for reccuring events like:
-recurrenceId
-...

**Comment by Dalker** [comment]
It's sad that this hasn't been implemented yet, in over two years :-( (coming here from one of the related, now closed, threads) - lack of recurrent events' exception handling leads to weird results, like leaving the regular schedule on while away for a week (as this is easier than copying all, then changing start/end dates of each copy - all because it's not yet possible to simply add one exception)

**Comment by bongosmurf** [comment]
Calendar handling is not trivial as it is and repeating event exceptions are complex as hell. Lotus Notes does this very well and has implemented a feature set which is very practical - and to my knowledge completely within specs - but is sadly not supported by most other SW including Outlook. This includes handling exceptions in recurring events without splitting them into two events, Letting you decide how recurring events falling on weekends or holidays are to be handled (such as leaving them as is, canceling or rescheduling them to the previous or next work day). Upon deletion of a recurring event, one can choose to cancel just the one event, all events, the one and all previous or the one and all following.
I'm not a Notes advocate nor am I suggesting that oC should implement all of this. I'm just saying I've come to appreciate this feature set in my work setting.

**Comment by DeepDiver1975** [comment]
Please reopen in calendar repo is still valid - THX
